### ISSUE TITLE
Ros2 definitions key should be 3-component type names

### ISSUE THREAD

**Issue by Chastrlove** [foxglove/rosmsg-msgs-common#12]
**Description**
Hello, I am a ROS2 beginner, and I recently encountered an issue while using Studio. I often see the error `datatype not found in geometry_msgs/msg/Point32`. After debugging, I found that this is caused by the inability to find the ROS2 definition. I came across this repository, and my question is: why is the ROS2 definition key not a three-layer structure, such as `geometry_msgs/msg/Point32`, but instead `geometry_msgs/Point32`? .

I noticed that the official ROS2 definitions use a three-layer structure, and they automatically add the "/msg" to the msg_type.
https://docs.ros2.org/galactic/api/geometry_msgs/msg/PoseStamped.html
<img width="930" alt="image" src="https://user-images.githubusercontent.com/17813559/234225783-a6077efd-9d51-4b35-a92e-b734592b31d5.png">

Could you please help me understand this? Thank you!

- Version: @foxglove/rosmsg-msgs-common@3.0.0
- Platform: Mac Chrome 112.0.5615.137 (arm64)

**Steps To Reproduce**

![image](https://user-images.githubusercontent.com/17813559/234221649-b6783a81-0903-4a74-a914-dc42faea7e99.png)

**Expected Behavior**
![image](https://user-images.githubusercontent.com/17813559/234226671-40813b87-fb44-42d0-b58b-0ab15fdc4e5e.png)

To be a 3-component type name

**Comment by jtbandes** [comment]
Please share sample data and steps to reproduce the error message you received in Studio.

**Comment by defunctzombie** [comment]
Closing for lack of response. We are happy to re-visit if you can share more details as asked.
