### ISSUE TITLE
Add ROS2 types

### ISSUE THREAD

**Issue by jhurliman** [foxglove/rosmsg-msgs-common#2]
This library currently only exports ROS1 common message definitions. ROS2 definitions should be exported as well (under a separate export name), with maps for both the "Type Name" (`builtin_interfaces/Time`) and the "Data Type" (`builtin_interfaces/msg/Time`).

**Comment by defunctzombie** [comment]
Maybe we should have ros1-msgs-common and ros2-msgs-common? It sounds like ros2 might be diverging enough in message format that we should treat these like two separate platforms.

**Comment by karanchahal** [comment]
Is this feature on track for release ? We are blocke3d as foxglove does not support ros2 message types.

**Comment by karanchahal** [comment]
As a motivating example, the header field is changed in `std_msgs` as it doesn't have the `seq` field. This affects all topics which inherit the Header field.
ROS1: https://github.com/ros/std_msgs/blob/kinetic-devel/msg/Header.msg
ROS2: https://github.com/ros2/common_interfaces/blob/master/std_msgs/msg/Header.msg

**Comment by defunctzombie** [comment]
@karanchahal What are you blocked on with this functionality within Studio?

> We are blocke3d as foxglove does not support ros2 message types.

I'm trying to understand what is blocked for you to use ROS2? We do support ROS2 in Foxglove Studio.

**Comment by jtbandes** [comment]
@defunctzombie I believe the specific issue is represented in https://github.com/foxglove/studio/issues/3170 / https://github.com/foxglove/studio/issues/2834. I don't think this ticket is really related to these issues.
