### ISSUE TITLE
support custom message types?

### ISSUE THREAD

**Issue by Elaine87** [foxglove/rosmsg-msgs-common#6]
How do I support adding custom message types? Our company use the message datatype  is livox_ros_driver/CustomMsg. Foxglove's 3D data type is not supported  livox_ros_driver/CustomMsg.

**Comment by Elaine87** [comment]
![image](https://user-images.githubusercontent.com/3049861/149313125-7b259995-5b6b-419c-92e8-0b0c3722fe5a.png)
![image](https://user-images.githubusercontent.com/3049861/149313232-82f9e333-dd7e-4f54-9e44-2dae496835eb.png)

**Comment by defunctzombie** [comment]
Hi @Elaine87 - This repo is only for the common message types in ROS1. Is your question about support in Foxglove Studio for your custom message types? Sorry but I don't fully understand the question.

**Comment by Elaine87** [comment]
> Hi @Elaine87 - This repo is only for the common message types in ROS1. Is your question about support in Foxglove Studio for your custom message types? Sorry but I don't fully understand the question.

 Thank you for your reply!  Yes, My question is  how to support   my custom message types(Livox_ros_driver pointcloud dataType: Livox_ros_driver/CustomMsg ) in Foxglove Studio?

**Comment by defunctzombie** [comment]
@Elaine87 lets move the discussion over to https://github.com/foxglove/studio/discussions or you can join our Studio slack channel (https://foxglove.dev/slack) and we can help you out there.

One thing we'll need to know is how you are loading data into Studio. Ros 1 bag files? Ros 2 .db3 files? And what you mean by supporting the custom message (i.e. viewing in a particular panel?).

**Comment by Elaine87** [comment]
> )

Ok, thank you! I have move this isuue to https://github.com/foxglove/studio/discussions/2670
----------------------------------------------------------------------------------
My bag is local Ros1 bag file. I want to know how to support in 3D pannel.
